- name: push to stack
  ansible.builtin.set_fact:
    my_stack: "{{ my_stack | default([]) + [local | default({})] }}"

- name: initialize local
  ansible.builtin.set_fact:
    local: "{{ input | default({}) }}"

- ansible.builtin.include_role:
    name: "{{ name }}"

- name: restore local
  ansible.builtin.set_fact:
    local: "{{ my_stack[-1] }}"

- name: pop from stack
  ansible.builtin.set_fact:
    my_stack: "{{ my_stack[:-1] }}"
